namespace BattleRunner.Core.Text
{
    /// <summary>
    /// The three tables, authored by hand.
    ///
    /// HOW TO READ AN ENTRY. `{0}`, `{1}` are values filled at runtime and must survive
    /// translation — the tests check that. A `|` separates plural variants: two for English and
    /// Hebrew (one, other), three for Russian (one, few, many), and <see cref="Plural"/> explains
    /// why Russian's are not a ternary.
    ///
    /// THE NUMBERS IN A STRING ARE LOAD-BEARING. Several of these quote a balance value that also
    /// exists as a StatModifier somewhere else, and a translation that mistyped one would state a
    /// rule the game does not follow. Every translation's digits are checked against the English
    /// source's, so a wrong number fails the build rather than misleading a player.
    ///
    /// HEBREW IS WRITTEN IN LOGICAL ORDER and without nikud. Vowel points are combining marks,
    /// and reordering a string for display puts a combining mark before the letter it belongs to;
    /// modern Hebrew interfaces do not use them anyway. A test enforces their absence.
    ///
    /// THE REGISTER: informal, and phrased so it never assumes the player's gender. Russian uses
    /// ты and imperatives, which are genderless. Hebrew imperatives are NOT, so instructions are
    /// phrased as infinitives — "להחליק את האגודל" rather than a masculine "החלק".
    /// </summary>
    public static class LocTables
    {
        public static readonly (LocKey Key, string Text)[] English =
        {
            // ---- the tutorial ---------------------------------------------------------
            (LocKey.TutorialSteerTitle, "DRAG TO STEER"),
            (LocKey.TutorialSteerDetail, "Slide your thumb left or right"),
            (LocKey.TutorialGateTitle, "TAKE THE BIGGER GATE"),
            (LocKey.TutorialGateDetail, "Blue adds, gold multiplies, red takes"),
            (LocKey.TutorialCastTitle, "FLICK UP TO CAST"),
            (LocKey.TutorialCastDetail, "Lift your thumb, then swipe up fast"),
            (LocKey.TutorialBlockTitle, "FLICK DOWN TO BLOCK"),
            (LocKey.TutorialBlockDetail, "Lift your thumb, then swipe down fast"),

            // ---- the four heroes ------------------------------------------------------
            (LocKey.HeroWardenName, "WARDEN"),
            (LocKey.HeroWardenTagline, "Holds the line. Two shields, and a blocked ambush joins you."),
            (LocKey.HeroAshcallerName, "ASHCALLER"),
            (LocKey.HeroAshcallerTagline, "Burns the road ahead. Two spells, and they reach further."),
            (LocKey.HeroHoundmasterName, "HOUNDMASTER"),
            (LocKey.HeroHoundmasterTagline, "Two hounds at the flank. Every recruit gate pays more."),
            (LocKey.HeroRevenantName, "REVENANT"),
            (LocKey.HeroRevenantTagline, "The fallen come back. What you lose, you mostly get again."),

            // ---- the eight worlds -----------------------------------------------------
            (LocKey.WorldAshenRoad, "The Ashen Road"),
            (LocKey.WorldThistlewood, "Thistlewood"),
            (LocKey.WorldSunkenCrypt, "The Sunken Crypt"),
            (LocKey.WorldEmberFields, "Ember Fields"),
            (LocKey.WorldBoneWastes, "The Bone Wastes"),
            (LocKey.WorldFrozenReach, "The Frozen Reach"),
            (LocKey.WorldBloodMarsh, "The Blood Marsh"),
            (LocKey.WorldThroneOfDust, "The Throne of Dust"),

            // ---- boss affixes ---------------------------------------------------------
            (LocKey.AffixFrenzied, "Frenzied"),
            (LocKey.AffixArmoured, "Armoured"),
            (LocKey.AffixVampiric, "Vampiric"),
            (LocKey.AffixHaunted, "Haunted"),
            (LocKey.AffixColossal, "Colossal"),
            (LocKey.AffixDecorate, "{0} {1}"),

            // ---- paragon --------------------------------------------------------------
            (LocKey.ParagonMight, "Might"),
            (LocKey.ParagonVigor, "Vigor"),
            (LocKey.ParagonGates, "Gates"),
            (LocKey.ParagonFortune, "Fortune"),
            (LocKey.ParagonFocus, "Focus"),
            (LocKey.ParagonSpeed, "Speed"),
            (LocKey.ParagonUnknownPath, "Unknown path"),
            (LocKey.ParagonNeedKeystone, "Reach a keystone first"),
            (LocKey.ParagonCostsPoints, "Costs {0} point|Costs {0} points"),

            // ---- the talent tree ------------------------------------------------------
            (LocKey.TalentWlEdgeName, "Keen Edge"),
            (LocKey.TalentWlEdgeDesc, "+3 Might"),
            (LocKey.TalentWlFocusName, "Cold Focus"),
            (LocKey.TalentWlFocusDesc, "+3% Focus"),
            (LocKey.TalentWlSpiteName, "Spite"),
            (LocKey.TalentWlSpiteDesc, "+6% spell damage"),
            (LocKey.TalentWlCleaveName, "Cleave"),
            (LocKey.TalentWlCleaveDesc, "+4% Might"),
            (LocKey.TalentWlTemperName, "Temper"),
            (LocKey.TalentWlTemperDesc, "+8% spell damage"),
            (LocKey.TalentWlGrindName, "Whetstone"),
            (LocKey.TalentWlGrindDesc, "+5 Might"),
            (LocKey.TalentWlHasteName, "Quickened"),
            (LocKey.TalentWlHasteDesc, "+4% Focus"),
            (LocKey.TalentWlWrathName, "Wrath"),
            (LocKey.TalentWlWrathDesc, "+5% Might"),
            (LocKey.TalentWlRuinName, "Ruin"),
            (LocKey.TalentWlRuinDesc, "+7 Might"),
            (LocKey.TalentWlSurgeName, "Surge"),
            (LocKey.TalentWlSurgeDesc, "+10% spell damage"),
            (LocKey.TalentWlMaliceName, "Malice"),
            (LocKey.TalentWlMaliceDesc, "+6% Might"),
            (LocKey.TalentWlVenomName, "Venom"),
            (LocKey.TalentWlVenomDesc, "+12% spell damage"),
            (LocKey.TalentWlUrgencyName, "Urgency"),
            (LocKey.TalentWlUrgencyDesc, "+5% Focus"),
            (LocKey.TalentWdHideName, "Thick Hide"),
            (LocKey.TalentWdHideDesc, "+18 Vigor"),
            (LocKey.TalentWdGuardName, "Guarded"),
            (LocKey.TalentWdGuardDesc, "Packs cost 4% less"),
            (LocKey.TalentWdBraceName, "Brace"),
            (LocKey.TalentWdBraceDesc, "Shield holds 0.2s longer"),
            (LocKey.TalentWdPlateName, "Plated"),
            (LocKey.TalentWdPlateDesc, "+4% Vigor"),
            (LocKey.TalentWdBrambleName, "Bramble"),
            (LocKey.TalentWdBrambleDesc, "Packs cost 5% less"),
            (LocKey.TalentWdStoneName, "Stoneblood"),
            (LocKey.TalentWdStoneDesc, "+24 Vigor"),
            (LocKey.TalentWdWardName, "Warded"),
            (LocKey.TalentWdWardDesc, "Shield holds 0.25s longer"),
            (LocKey.TalentWdScarName, "Scarred"),
            (LocKey.TalentWdScarDesc, "Packs cost 5% less"),
            (LocKey.TalentWdReadyName, "At the Ready"),
            (LocKey.TalentWdReadyDesc, "Shields return 4% sooner"),
            (LocKey.TalentWdBastionName, "Bastion"),
            (LocKey.TalentWdBastionDesc, "+6% Vigor"),
            (LocKey.TalentWdThornsName, "Thorns"),
            (LocKey.TalentWdThornsDesc, "12% reflect"),
            (LocKey.TalentWdIronName, "Ironbound"),
            (LocKey.TalentWdIronDesc, "+34 Vigor"),
            (LocKey.TalentWdDenyName, "Denial"),
            (LocKey.TalentWdDenyDesc, "Packs cost 6% less"),
            (LocKey.TalentWdShellName, "Shell"),
            (LocKey.TalentWdShellDesc, "10% shatter"),
            (LocKey.TalentZlAvariceName, "Avarice"),
            (LocKey.TalentZlAvariceDesc, "+3% from every gate"),
            (LocKey.TalentZlStrideName, "Stride"),
            (LocKey.TalentZlStrideDesc, "+2% speed"),
            (LocKey.TalentZlLuckName, "Fortune"),
            (LocKey.TalentZlLuckDesc, "+6% rare loot"),
            (LocKey.TalentZlGreedName, "Greed"),
            (LocKey.TalentZlGreedDesc, "+4% from every gate"),
            (LocKey.TalentZlLodestoneName, "Lodestone"),
            (LocKey.TalentZlLodestoneDesc, "Gates reach 0.12 m wider"),
            (LocKey.TalentZlTitheName, "Tithe"),
            (LocKey.TalentZlTitheDesc, "+5% from every gate"),
            (LocKey.TalentZlOmenName, "Omen"),
            (LocKey.TalentZlOmenDesc, "+8% rare loot"),
            (LocKey.TalentZlFervourName, "Fervour"),
            (LocKey.TalentZlFervourDesc, "4% gate crit"),
            (LocKey.TalentZlHungerName, "Hunger"),
            (LocKey.TalentZlHungerDesc, "+6% from every gate"),
            (LocKey.TalentZlPullName, "Pull"),
            (LocKey.TalentZlPullDesc, "Gates reach 0.15 m wider"),
            (LocKey.TalentZlRaptureName, "Rapture"),
            (LocKey.TalentZlRaptureDesc, "+7% from every gate"),
            (LocKey.TalentZlFrenzyName, "Frenzy"),
            (LocKey.TalentZlFrenzyDesc, "+3% speed"),
            (LocKey.TalentZlCascadeName, "Spiral"),
            (LocKey.TalentZlCascadeDesc, "+8% chain"),
            (LocKey.TalentWlEchoName, "Echoing Word"),
            (LocKey.TalentWlEchoDesc, "12% chance the spell casts twice"),
            (LocKey.TalentWlLanceName, "Sunder"),
            (LocKey.TalentWlLanceDesc, "+22% spell damage, +6 Might"),
            (LocKey.TalentWlQuiverName, "Full Quiver"),
            (LocKey.TalentWlQuiverDesc, "Hold a second spell"),
            (LocKey.TalentWlExecuteName, "Executioner"),
            (LocKey.TalentWlExecuteDesc, "A boss under 8% health dies outright"),
            (LocKey.TalentWlReapName, "Reaper's Due"),
            (LocKey.TalentWlReapDesc, "Execute threshold +7%"),
            (LocKey.TalentWlSwiftName, "Swiftness"),
            (LocKey.TalentWlSwiftDesc, "+9% Focus, 10% spell echo"),
            (LocKey.TalentWlArsenalName, "Arsenal"),
            (LocKey.TalentWlArsenalDesc, "Hold a third spell"),
            (LocKey.TalentWlCarnageName, "Carnage"),
            (LocKey.TalentWlCarnageDesc, "+14 Might and +20% spell damage"),
            (LocKey.TalentWdShatterName, "Shatterguard"),
            (LocKey.TalentWdShatterDesc, "14% chance a pack shatters and costs nothing"),
            (LocKey.TalentWdDoubleguardName, "Doubleguard"),
            (LocKey.TalentWdDoubleguardDesc, "Hold a second shield raise"),
            (LocKey.TalentWdBulwarkName, "Bulwark"),
            (LocKey.TalentWdBulwarkDesc, "Shield holds 1s longer, +30 Vigor"),
            (LocKey.TalentWdReflectName, "Riposte"),
            (LocKey.TalentWdReflectDesc, "A blocked blow returns 25% of it to the boss"),
            (LocKey.TalentWdWindName, "Second Wind"),
            (LocKey.TalentWdWindDesc, "Once per run, death restores 30% of your army"),
            (LocKey.TalentWdAegisName, "Aegis"),
            (LocKey.TalentWdAegisDesc, "Shield holds 1.4s longer, 18% shatter"),
            (LocKey.TalentWdTriguardName, "Triguard"),
            (LocKey.TalentWdTriguardDesc, "Hold a third shield raise"),
            (LocKey.TalentWdUnbrokenName, "Unbroken"),
            (LocKey.TalentWdUnbrokenDesc, "+70 Vigor, packs cost 12% less"),
            (LocKey.TalentZlCritName, "Zealotry"),
            (LocKey.TalentZlCritDesc, "10% chance a gate counts double"),
            (LocKey.TalentZlZealName, "Zeal"),
            (LocKey.TalentZlZealDesc, "+12% speed, +8% from gates"),
            (LocKey.TalentZlChainName, "Cascade"),
            (LocKey.TalentZlChainDesc, "Each consecutive x gate adds 15% more"),
            (LocKey.TalentZlHoardName, "Hoard"),
            (LocKey.TalentZlHoardDesc, "Overflow past the cap returns 25% as boss damage"),
            (LocKey.TalentZlSwarmName, "Swarm"),
            (LocKey.TalentZlSwarmDesc, "+18% from gates, 12% gate crit"),
            (LocKey.TalentZlLegionName, "Legion"),
            (LocKey.TalentZlLegionDesc, "+25% from gates, +20% rare loot"),
            (LocKey.TalentWlAnnihilationName, "ANNIHILATION"),
            (LocKey.TalentWlAnnihilationDesc, "+40% Might, +60% spell damage"),
            (LocKey.TalentWlHeadsmanName, "THE HEADSMAN"),
            (LocKey.TalentWlHeadsmanDesc, "Execute threshold +20%"),
            (LocKey.TalentWlTempestName, "TEMPEST"),
            (LocKey.TalentWlTempestDesc, "Two more spells, 45% echo, +25% Focus"),
            (LocKey.TalentWdUndyingName, "UNDYING"),
            (LocKey.TalentWdUndyingDesc, "+120 Vigor, second wind restores 55%"),
            (LocKey.TalentWdImmovableName, "IMMOVABLE"),
            (LocKey.TalentWdImmovableDesc, "Packs cost 40% less, 30% shatter"),
            (LocKey.TalentWdMirrorName, "MIRROR OF THORNS"),
            (LocKey.TalentWdMirrorDesc, "Two more shield raises, blocked blows return 90%"),
            (LocKey.TalentZlMultiplicationName, "MULTIPLICATION"),
            (LocKey.TalentZlMultiplicationDesc, "+55% from gates, 25% gate crit"),
            (LocKey.TalentZlAvalancheName, "AVALANCHE"),
            (LocKey.TalentZlAvalancheDesc, "Chain +60%, gates reach 0.5 m wider"),
            (LocKey.TalentZlCovetousName, "COVETOUS"),
            (LocKey.TalentZlCovetousDesc, "Overflow returns 90%, +60% rare loot"),
            (LocKey.TalentCrWarpriestName, "War Priest"),
            (LocKey.TalentCrWarpriestDesc, "+10 Might, +8% from gates"),
            (LocKey.TalentCrCrusaderName, "Crusader"),
            (LocKey.TalentCrCrusaderDesc, "+40 Vigor, +12% spell damage"),
            (LocKey.TalentCrPilgrimName, "Pilgrim"),
            (LocKey.TalentCrPilgrimDesc, "Packs cost 10% less, +6% speed"),
            (LocKey.TalentCrMartyrName, "Martyr"),
            (LocKey.TalentCrMartyrDesc, "Blocked blows return 30%, +12 Might"),
            (LocKey.TalentCrProphetName, "Prophet"),
            (LocKey.TalentCrProphetDesc, "Overflow returns 30%, +18% spell damage"),
            (LocKey.TalentCrShepherdName, "Shepherd"),
            (LocKey.TalentCrShepherdDesc, "18% shatter, +14% from gates"),
            (LocKey.TalentCrApostleName, "Apostle"),
            (LocKey.TalentCrApostleDesc, "Execute +6%, chain +20%"),
            (LocKey.TalentCrPaladinName, "Paladin"),
            (LocKey.TalentCrPaladinDesc, "+80 Vigor, +18 Might, shield holds 0.8s longer"),

            // ---- the talent tree: branches and refusals -------------------------------
            (LocKey.BranchWarlord, "Warlord"),
            (LocKey.BranchWarden, "Warden"),
            (LocKey.BranchZealot, "Zealot"),
            (LocKey.BranchCrossroads, "Crossroads"),
            (LocKey.TalentUnknown, "Unknown talent"),
            (LocKey.TalentFullyRanked, "Fully ranked"),
            (LocKey.TalentNoPoints, "No points to spend"),
            (LocKey.TalentRuledOut, "{0} rules it out"),
            (LocKey.TalentNeedsBoth, "Needs {0} points in {1} and {2}"),
            (LocKey.TalentNeedsBranch, "Needs {0} points in {1}"),
            (LocKey.TalentNotLearned, "Not learned"),
            (LocKey.TalentUnlearnFirst, "Unlearn {0} first"),

            // ---- stat names, and the two shapes a stat value is written in ------------
            (LocKey.StatDamage, "Might"),
            (LocKey.StatHealth, "Vigor"),
            (LocKey.StatCooldown, "Focus"),
            (LocKey.StatSpellPower, "Spell"),
            (LocKey.StatGateYield, "Gates"),
            (LocKey.StatRunSpeed, "Speed"),
            (LocKey.StatEnemyResist, "Resist"),
            (LocKey.StatShieldDuration, "Shield"),
            (LocKey.StatSpellCharges, "Spell Charges"),
            (LocKey.StatShieldCharges, "Shield Charges"),
            (LocKey.StatFortune, "Fortune"),
            (LocKey.StatGateCrit, "Gate Crit"),
            (LocKey.StatOverflowBank, "Overflow"),
            (LocKey.StatChainMultiply, "Chain"),
            (LocKey.StatMagnetism, "Magnetism"),
            (LocKey.StatPackShatter, "Shatter"),
            (LocKey.StatSecondWind, "Second Wind"),
            (LocKey.StatExecute, "Execute"),
            (LocKey.StatSpellEcho, "Echo"),
            (LocKey.StatShieldReflect, "Reflect"),
            (LocKey.StatAffixPercent, "{0}{1}% {2}"),
            (LocKey.StatAffixFlat, "{0}{1} {2}"),
            (LocKey.StatTotalPercent, "{0} {1}%"),
            (LocKey.StatTotalFlat, "{0} {1}"),
            (LocKey.StatNone, "No bonuses"),

            // ---- the screens, the loot, and the authored content ----------------------
            (LocKey.GameTitle, "BATTLE RUNNER"),
            (LocKey.MenuTagline, "march. multiply. slay."),
            (LocKey.MenuSetForth, "SET FORTH"),
            (LocKey.MenuChangeSlot, "CHANGE SLOT"),
            (LocKey.MenuSoundOn, "SOUND ON"),
            (LocKey.MenuSoundOff, "SOUND OFF"),
            (LocKey.MenuLanguage, "LANGUAGE"),
            (LocKey.MenuLevelLine, "Level {0} — {1}"),
            (LocKey.SlotChooseWar, "choose your war"),
            (LocKey.SlotErase, "ERASE"),
            (LocKey.ConfirmSure, "SURE?"),
            (LocKey.HeroChooseTitle, "CHOOSE YOUR CHAMPION"),
            (LocKey.HeroChooseNote, "this choice is for the life of this save"),
            (LocKey.HeroShowMe, "SHOW ME"),
            (LocKey.HeroBegin, "BEGIN"),
            (LocKey.HudSpellReady, "SPELL ^ {0}"),
            (LocKey.HudSpellRefill, "SPELL {0} {1}"),
            (LocKey.HudShielded, "SHIELDED {0}"),
            (LocKey.HudShieldReady, "SHIELD v {0}"),
            (LocKey.HudShieldRefill, "SHIELD {0} {1}"),
            (LocKey.HudRound, "{0}-{1}   {2}"),
            (LocKey.HudBossAwaits, "{0} AWAITS"),
            (LocKey.HudBossUnknown, "SOMETHING"),
            (LocKey.LootBossYields, "THE BOSS YIELDS..."),
            (LocKey.LootBossYieldsTwice, "THE BOSS YIELDS... TWICE!"),
            (LocKey.LootSpoils, "SPOILS OF THE ROAD"),
            (LocKey.LootDoubleAd, "DOUBLE LOOT  (AD)"),
            (LocKey.LootAutoEquip, "AUTO-EQUIP & CONTINUE"),
            (LocKey.LootItemLine, "{0}\n<size=30>{1} {2}</size>"),
            (LocKey.LootPowerEquipped, "Item Power {0}  — equipped!"),
            (LocKey.LootPowerKept, "Item Power {0}  — kept in inventory"),
            (LocKey.RarityCommon, "Common"),
            (LocKey.RarityRare, "Rare"),
            (LocKey.RarityEpic, "Epic"),
            (LocKey.RarityLegendary, "Legendary"),
            (LocKey.GearSlotWeapon, "Weapon"),
            (LocKey.GearSlotArmor, "Armor"),
            (LocKey.GearSlotRelic, "Relic"),
            (LocKey.GearNone, "no gear yet"),
            (LocKey.Dash, "—"),
            (LocKey.ResurrectFallen, "YOUR FORCE HAS FALLEN"),
            (LocKey.ResurrectAd, "RESURRECT  (AD)"),
            (LocKey.ResurrectGiveUp, "ACCEPT DEFEAT"),
            (LocKey.TreeTitle, "GROW STRONGER"),
            (LocKey.TreeContinue, "CONTINUE"),
            (LocKey.TreeForgetAll, "FORGET ALL"),
            (LocKey.TreeEndless, "ENDLESS — every point still counts"),
            (LocKey.TabWarlord, "WARLORD"),
            (LocKey.TabWarden, "WARDEN"),
            (LocKey.TabZealot, "ZEALOT"),
            (LocKey.TabHybrid, "HYBRID"),
            (LocKey.TabParagon, "PARAGON"),
            (LocKey.TreeNeedsBothTier, "NEEDS {0} IN BOTH BRANCHES"),
            (LocKey.TreeTierLine, "TIER {0} · {1} POINTS IN BRANCH"),
            (LocKey.TreeKeystoneChoose, "KEYSTONE — CHOOSE ONE"),
            (LocKey.TreeReady, "READY"),
            (LocKey.TreeTapAgain, "TAP - AGAIN"),
            (LocKey.TreePointsToSpend, "{0} point to spend|{0} points to spend"),
            (LocKey.TreePointsSpent, "{0} point spent · tap - on a talent to take one back|{0} points spent · tap - on a talent to take one back"),
            (LocKey.TreeParagonRanks, "{0} paragon rank · each rank costs more and gives a little less|{0} paragon ranks · each rank costs more and gives a little less"),
            (LocKey.TreeParagonLocked, "Locked until you take a keystone"),
            (LocKey.TreeParagonOpens, "Paragon opens the moment you take a keystone."),
            (LocKey.TreeSpendFour, "Spend four points in a branch to open its next tier."),
            (LocKey.TreeRankLine, "Rank {0} · {1} · next costs {2}"),
            (LocKey.TreeGiveBack, "Tap - again to give back a rank of {0}."),
            (LocKey.TreeRefunded, "{0} refunded."),
            (LocKey.TreeDeepened, "{0} deepened."),
            (LocKey.TreeForgotten, "Everything forgotten. Spend the points again."),
            (LocKey.TreeForgetConfirm, "Forget every talent and paragon rank, and take all the points back?"),
            (LocKey.StatMightDesc, "Raw damage dealt by your hero and horde."),
            (LocKey.StatVigorDesc, "Cushions your force against boss blows."),
            (LocKey.StatFocusDesc, "Shortens spell and shield cooldowns."),
            (LocKey.BossBoneColossus, "Bone Colossus"),
            (LocKey.BossEmberLich, "Ember Lich"),
            (LocKey.BossGraveWarden, "Grave Warden"),
            (LocKey.BossHollowLeech, "Hollow Leech"),
            (LocKey.BossPaleShepherd, "Pale Shepherd"),
            (LocKey.BossGoreHound, "Gore Hound"),
            (LocKey.LevelAshenRoad, "The Ashen Road"),
            (LocKey.LevelGallowsMire, "Gallows Mire"),
            (LocKey.LevelSunkenCrypt, "The Sunken Crypt"),
            (LocKey.LevelEmberFields, "Ember Fields"),
            (LocKey.LevelThroneOfDust, "Throne of Dust"),
            (LocKey.LevelWeepingGate, "The Weeping Gate"),
            (LocKey.GearWpnRustedCleaverName, "Rusted Cleaver"),
            (LocKey.GearWpnRustedCleaverFlavor, "Still remembers the war it lost."),
            (LocKey.GearWpnGravediggerAxeName, "Gravedigger's Axe"),
            (LocKey.GearWpnGravediggerAxeFlavor, "Blunt from honest, grim work."),
            (LocKey.GearWpnCinderBladeName, "Cinder Blade"),
            (LocKey.GearWpnCinderBladeFlavor, "Warm to the touch. Always."),
            (LocKey.GearWpnSoulreaverName, "Soulreaver"),
            (LocKey.GearWpnSoulreaverFlavor, "It drinks. You wield."),
            (LocKey.GearWpnDoombringerName, "Doombringer"),
            (LocKey.GearWpnDoombringerFlavor, "The last blade its forger ever made."),
            (LocKey.GearArmTatteredHauberkName, "Tattered Hauberk"),
            (LocKey.GearArmTatteredHauberkFlavor, "More gaps than mail."),
            (LocKey.GearArmBoneVestName, "Bone-Studded Vest"),
            (LocKey.GearArmBoneVestFlavor, "The bones are not decorative."),
            (LocKey.GearArmIronbarkPlateName, "Ironbark Plate"),
            (LocKey.GearArmIronbarkPlateFlavor, "Grown, not forged."),
            (LocKey.GearArmWraithmailName, "Wraithmail"),
            (LocKey.GearArmWraithmailFlavor, "Weightless. Whispering."),
            (LocKey.GearArmAegisFallenKingName, "Aegis of the Fallen King"),
            (LocKey.GearArmAegisFallenKingFlavor, "He fell. It didn't."),
            (LocKey.GearRelCrackedSkullName, "Cracked Skull Charm"),
            (LocKey.GearRelCrackedSkullFlavor, "Its previous owner had worse luck."),
            (LocKey.GearRelEmberTalismanName, "Ember Talisman"),
            (LocKey.GearRelEmberTalismanFlavor, "A pocketful of dying fire."),
            (LocKey.GearRelHollowIdolName, "Hollow Idol"),
            (LocKey.GearRelHollowIdolFlavor, "Something used to live inside."),
            (LocKey.GearRelEyeOfAbyssName, "Eye of the Abyss"),
            (LocKey.GearRelEyeOfAbyssFlavor, "It blinks when you cast."),
            (LocKey.GearRelCrownOfEmbersName, "Crown of Embers"),
            (LocKey.GearRelCrownOfEmbersFlavor, "Rule nothing. Burn everything."),

            // ---- save slots -----------------------------------------------------------
            (LocKey.SlotNumber, "SLOT {0}"),
            (LocKey.SlotNewGame, "New game"),
            (LocKey.SlotLevel, "Level {0}"),
            (LocKey.SlotTalents, "{0} talent|{0} talents"),
            (LocKey.SlotUnspent, "{0} unspent")
        };

        public static readonly (LocKey Key, string Text)[] Russian =
        {
            // ---- the tutorial ---------------------------------------------------------
            (LocKey.TutorialSteerTitle, "ВЕДИ ПАЛЬЦЕМ"),
            (LocKey.TutorialSteerDetail, "Веди большой палец влево или вправо"),
            (LocKey.TutorialGateTitle, "БЕРИ ВОРОТА ПОБОЛЬШЕ"),
            (LocKey.TutorialGateDetail, "Синие прибавляют, золотые умножают, красные отнимают"),
            (LocKey.TutorialCastTitle, "ВЗМАХ ВВЕРХ — ЗАКЛИНАНИЕ"),
            (LocKey.TutorialCastDetail, "Оторви палец, затем резко проведи вверх"),
            (LocKey.TutorialBlockTitle, "ВЗМАХ ВНИЗ — ЩИТ"),
            (LocKey.TutorialBlockDetail, "Оторви палец, затем резко проведи вниз"),

            // ---- the four heroes ------------------------------------------------------
            (LocKey.HeroWardenName, "СТРАЖ"),
            (LocKey.HeroWardenTagline, "Держит строй. Два щита, и отражённая засада встаёт в ряды."),
            (LocKey.HeroAshcallerName, "ПЕПЛОЗВАТЕЦ"),
            (LocKey.HeroAshcallerTagline, "Выжигает путь впереди. Два заклинания, и бьют они дальше."),
            (LocKey.HeroHoundmasterName, "ПСАРЬ"),
            (LocKey.HeroHoundmasterTagline, "Два пса на фланге. Любые ворота набора дают больше."),
            (LocKey.HeroRevenantName, "ВОССТАВШИЙ"),
            (LocKey.HeroRevenantTagline, "Павшие возвращаются. Потерянное почти всё вернётся."),

            // ---- the eight worlds -----------------------------------------------------
            (LocKey.WorldAshenRoad, "Пепельный тракт"),
            (LocKey.WorldThistlewood, "Чертополошье"),
            (LocKey.WorldSunkenCrypt, "Затонувший склеп"),
            (LocKey.WorldEmberFields, "Тлеющие поля"),
            (LocKey.WorldBoneWastes, "Костяные пустоши"),
            (LocKey.WorldFrozenReach, "Стылый предел"),
            (LocKey.WorldBloodMarsh, "Кровавая топь"),
            (LocKey.WorldThroneOfDust, "Престол праха"),

            // ---- boss affixes ---------------------------------------------------------
            // Masculine forms throughout, which is not an accident: every boss name in the
            // Russian table is a masculine noun, including the Hollow Leech — rendered as
            // "Кровосос" rather than the feminine "Пиявка" precisely so one adjective form
            // serves all six. Russian adjectives agree in gender, and a table with two forms
            // per affix would need a gender field on every boss to pick between them.
            (LocKey.AffixFrenzied, "Яростный"),
            (LocKey.AffixArmoured, "Бронированный"),
            (LocKey.AffixVampiric, "Вампирический"),
            (LocKey.AffixHaunted, "Одержимый"),
            (LocKey.AffixColossal, "Колоссальный"),
            (LocKey.AffixDecorate, "{0} {1}"),

            // ---- paragon --------------------------------------------------------------
            (LocKey.ParagonMight, "Мощь"),
            (LocKey.ParagonVigor, "Живучесть"),
            (LocKey.ParagonGates, "Ворота"),
            (LocKey.ParagonFortune, "Удача"),
            (LocKey.ParagonFocus, "Сосредоточение"),
            (LocKey.ParagonSpeed, "Скорость"),
            (LocKey.ParagonUnknownPath, "Неизвестный путь"),
            (LocKey.ParagonNeedKeystone, "Сначала возьми краеугольный талант"),
            (LocKey.ParagonCostsPoints, "Стоит {0} очко|Стоит {0} очка|Стоит {0} очков"),

            // ---- the talent tree ------------------------------------------------------
            (LocKey.TalentWlEdgeName, "Острое лезвие"),
            (LocKey.TalentWlEdgeDesc, "+3 Мощи"),
            (LocKey.TalentWlFocusName, "Холодный расчёт"),
            (LocKey.TalentWlFocusDesc, "+3% Сосредоточения"),
            (LocKey.TalentWlSpiteName, "Злоба"),
            (LocKey.TalentWlSpiteDesc, "+6% урона заклинаний"),
            (LocKey.TalentWlCleaveName, "Раскол"),
            (LocKey.TalentWlCleaveDesc, "+4% Мощи"),
            (LocKey.TalentWlTemperName, "Закалка"),
            (LocKey.TalentWlTemperDesc, "+8% урона заклинаний"),
            (LocKey.TalentWlGrindName, "Точильный камень"),
            (LocKey.TalentWlGrindDesc, "+5 Мощи"),
            (LocKey.TalentWlHasteName, "Ускорение"),
            (LocKey.TalentWlHasteDesc, "+4% Сосредоточения"),
            (LocKey.TalentWlWrathName, "Гнев"),
            (LocKey.TalentWlWrathDesc, "+5% Мощи"),
            (LocKey.TalentWlRuinName, "Погибель"),
            (LocKey.TalentWlRuinDesc, "+7 Мощи"),
            (LocKey.TalentWlSurgeName, "Всплеск"),
            (LocKey.TalentWlSurgeDesc, "+10% урона заклинаний"),
            (LocKey.TalentWlMaliceName, "Коварство"),
            (LocKey.TalentWlMaliceDesc, "+6% Мощи"),
            (LocKey.TalentWlVenomName, "Яд"),
            (LocKey.TalentWlVenomDesc, "+12% урона заклинаний"),
            (LocKey.TalentWlUrgencyName, "Спешка"),
            (LocKey.TalentWlUrgencyDesc, "+5% Сосредоточения"),
            (LocKey.TalentWdHideName, "Толстая шкура"),
            (LocKey.TalentWdHideDesc, "+18 Живучести"),
            (LocKey.TalentWdGuardName, "Настороже"),
            (LocKey.TalentWdGuardDesc, "Отряды стоят на 4% меньше"),
            (LocKey.TalentWdBraceName, "Упор"),
            (LocKey.TalentWdBraceDesc, "Щит держится на 0.2 с дольше"),
            (LocKey.TalentWdPlateName, "Латы"),
            (LocKey.TalentWdPlateDesc, "+4% Живучести"),
            (LocKey.TalentWdBrambleName, "Терновник"),
            (LocKey.TalentWdBrambleDesc, "Отряды стоят на 5% меньше"),
            (LocKey.TalentWdStoneName, "Каменная кровь"),
            (LocKey.TalentWdStoneDesc, "+24 Живучести"),
            (LocKey.TalentWdWardName, "Оберег"),
            (LocKey.TalentWdWardDesc, "Щит держится на 0.25 с дольше"),
            (LocKey.TalentWdScarName, "Рубцы"),
            (LocKey.TalentWdScarDesc, "Отряды стоят на 5% меньше"),
            (LocKey.TalentWdReadyName, "Наготове"),
            (LocKey.TalentWdReadyDesc, "Щит возвращается на 4% быстрее"),
            (LocKey.TalentWdBastionName, "Бастион"),
            (LocKey.TalentWdBastionDesc, "+6% Живучести"),
            (LocKey.TalentWdThornsName, "Шипы"),
            (LocKey.TalentWdThornsDesc, "12% отражения"),
            (LocKey.TalentWdIronName, "Окованный железом"),
            (LocKey.TalentWdIronDesc, "+34 Живучести"),
            (LocKey.TalentWdDenyName, "Отказ"),
            (LocKey.TalentWdDenyDesc, "Отряды стоят на 6% меньше"),
            (LocKey.TalentWdShellName, "Панцирь"),
            (LocKey.TalentWdShellDesc, "10% раскола"),
            (LocKey.TalentZlAvariceName, "Алчность"),
            (LocKey.TalentZlAvariceDesc, "+3% от каждых ворот"),
            (LocKey.TalentZlStrideName, "Поступь"),
            (LocKey.TalentZlStrideDesc, "+2% скорости"),
            (LocKey.TalentZlLuckName, "Фортуна"),
            (LocKey.TalentZlLuckDesc, "+6% редкой добычи"),
            (LocKey.TalentZlGreedName, "Жадность"),
            (LocKey.TalentZlGreedDesc, "+4% от каждых ворот"),
            (LocKey.TalentZlLodestoneName, "Магнетит"),
            (LocKey.TalentZlLodestoneDesc, "Ворота тянутся на 0.12 м шире"),
            (LocKey.TalentZlTitheName, "Десятина"),
            (LocKey.TalentZlTitheDesc, "+5% от каждых ворот"),
            (LocKey.TalentZlOmenName, "Знамение"),
            (LocKey.TalentZlOmenDesc, "+8% редкой добычи"),
            (LocKey.TalentZlFervourName, "Пыл"),
            (LocKey.TalentZlFervourDesc, "4% крита ворот"),
            (LocKey.TalentZlHungerName, "Голод"),
            (LocKey.TalentZlHungerDesc, "+6% от каждых ворот"),
            (LocKey.TalentZlPullName, "Притяжение"),
            (LocKey.TalentZlPullDesc, "Ворота тянутся на 0.15 м шире"),
            (LocKey.TalentZlRaptureName, "Восторг"),
            (LocKey.TalentZlRaptureDesc, "+7% от каждых ворот"),
            (LocKey.TalentZlFrenzyName, "Исступление"),
            (LocKey.TalentZlFrenzyDesc, "+3% скорости"),
            (LocKey.TalentZlCascadeName, "Спираль"),
            (LocKey.TalentZlCascadeDesc, "+8% цепи"),
            (LocKey.TalentWlEchoName, "Эхо слова"),
            (LocKey.TalentWlEchoDesc, "12% шанс, что заклинание сработает дважды"),
            (LocKey.TalentWlLanceName, "Разлом"),
            (LocKey.TalentWlLanceDesc, "+22% урона заклинаний, +6 Мощи"),
            (LocKey.TalentWlQuiverName, "Полный колчан"),
            (LocKey.TalentWlQuiverDesc, "Держи второе заклинание"),
            (LocKey.TalentWlExecuteName, "Палач"),
            (LocKey.TalentWlExecuteDesc, "Босс ниже 8% здоровья гибнет сразу"),
            (LocKey.TalentWlReapName, "Плата жнецу"),
            (LocKey.TalentWlReapDesc, "Порог добивания +7%"),
            (LocKey.TalentWlSwiftName, "Проворство"),
            (LocKey.TalentWlSwiftDesc, "+9% Сосредоточения, 10% эха заклинаний"),
            (LocKey.TalentWlArsenalName, "Арсенал"),
            (LocKey.TalentWlArsenalDesc, "Держи третье заклинание"),
            (LocKey.TalentWlCarnageName, "Резня"),
            (LocKey.TalentWlCarnageDesc, "+14 Мощи и +20% урона заклинаний"),
            (LocKey.TalentWdShatterName, "Раскольный щит"),
            (LocKey.TalentWdShatterDesc, "14% шанс, что отряд рассыплется и не будет стоить ничего"),
            (LocKey.TalentWdDoubleguardName, "Двойная защита"),
            (LocKey.TalentWdDoubleguardDesc, "Держи второй подъём щита"),
            (LocKey.TalentWdBulwarkName, "Оплот"),
            (LocKey.TalentWdBulwarkDesc, "Щит держится на 1 с дольше, +30 Живучести"),
            (LocKey.TalentWdReflectName, "Рипост"),
            (LocKey.TalentWdReflectDesc, "Отражённый удар возвращает боссу 25% его силы"),
            (LocKey.TalentWdWindName, "Второе дыхание"),
            (LocKey.TalentWdWindDesc, "Раз за забег смерть возвращает 30% войска"),
            (LocKey.TalentWdAegisName, "Эгида"),
            (LocKey.TalentWdAegisDesc, "Щит держится на 1.4 с дольше, 18% раскола"),
            (LocKey.TalentWdTriguardName, "Тройная защита"),
            (LocKey.TalentWdTriguardDesc, "Держи третий подъём щита"),
            (LocKey.TalentWdUnbrokenName, "Несломленный"),
            (LocKey.TalentWdUnbrokenDesc, "+70 Живучести, отряды стоят на 12% меньше"),
            (LocKey.TalentZlCritName, "Фанатизм"),
            (LocKey.TalentZlCritDesc, "10% шанс, что ворота сочтутся дважды"),
            (LocKey.TalentZlZealName, "Рвение"),
            (LocKey.TalentZlZealDesc, "+12% скорости, +8% от ворот"),
            (LocKey.TalentZlChainName, "Каскад"),
            (LocKey.TalentZlChainDesc, "Каждые подряд идущие ворота x дают на 15% больше"),
            (LocKey.TalentZlHoardName, "Сокровищница"),
            (LocKey.TalentZlHoardDesc, "Излишек сверх предела возвращает 25% уроном по боссу"),
            (LocKey.TalentZlSwarmName, "Рой"),
            (LocKey.TalentZlSwarmDesc, "+18% от ворот, 12% крита ворот"),
            (LocKey.TalentZlLegionName, "Легион"),
            (LocKey.TalentZlLegionDesc, "+25% от ворот, +20% редкой добычи"),
            (LocKey.TalentWlAnnihilationName, "УНИЧТОЖЕНИЕ"),
            (LocKey.TalentWlAnnihilationDesc, "+40% Мощи, +60% урона заклинаний"),
            (LocKey.TalentWlHeadsmanName, "ГОЛОВОРУБ"),
            (LocKey.TalentWlHeadsmanDesc, "Порог добивания +20%"),
            (LocKey.TalentWlTempestName, "БУРЯ"),
            (LocKey.TalentWlTempestDesc, "Ещё два заклинания, 45% эха, +25% Сосредоточения"),
            (LocKey.TalentWdUndyingName, "БЕССМЕРТНЫЙ"),
            (LocKey.TalentWdUndyingDesc, "+120 Живучести, второе дыхание возвращает 55%"),
            (LocKey.TalentWdImmovableName, "НЕСОКРУШИМЫЙ"),
            (LocKey.TalentWdImmovableDesc, "Отряды стоят на 40% меньше, 30% раскола"),
            (LocKey.TalentWdMirrorName, "ЗЕРКАЛО ШИПОВ"),
            (LocKey.TalentWdMirrorDesc, "Ещё два подъёма щита, отражённые удары возвращают 90%"),
            (LocKey.TalentZlMultiplicationName, "УМНОЖЕНИЕ"),
            (LocKey.TalentZlMultiplicationDesc, "+55% от ворот, 25% крита ворот"),
            (LocKey.TalentZlAvalancheName, "ЛАВИНА"),
            (LocKey.TalentZlAvalancheDesc, "Цепь +60%, ворота тянутся на 0.5 м шире"),
            (LocKey.TalentZlCovetousName, "СТЯЖАТЕЛЬ"),
            (LocKey.TalentZlCovetousDesc, "Излишек возвращает 90%, +60% редкой добычи"),
            (LocKey.TalentCrWarpriestName, "Жрец войны"),
            (LocKey.TalentCrWarpriestDesc, "+10 Мощи, +8% от ворот"),
            (LocKey.TalentCrCrusaderName, "Крестоносец"),
            (LocKey.TalentCrCrusaderDesc, "+40 Живучести, +12% урона заклинаний"),
            (LocKey.TalentCrPilgrimName, "Пилигрим"),
            (LocKey.TalentCrPilgrimDesc, "Отряды стоят на 10% меньше, +6% скорости"),
            (LocKey.TalentCrMartyrName, "Мученик"),
            (LocKey.TalentCrMartyrDesc, "Отражённые удары возвращают 30%, +12 Мощи"),
            (LocKey.TalentCrProphetName, "Пророк"),
            (LocKey.TalentCrProphetDesc, "Излишек возвращает 30%, +18% урона заклинаний"),
            (LocKey.TalentCrShepherdName, "Пастырь"),
            (LocKey.TalentCrShepherdDesc, "18% раскола, +14% от ворот"),
            (LocKey.TalentCrApostleName, "Апостол"),
            (LocKey.TalentCrApostleDesc, "Добивание +6%, цепь +20%"),
            (LocKey.TalentCrPaladinName, "Паладин"),
            (LocKey.TalentCrPaladinDesc, "+80 Живучести, +18 Мощи, щит держится на 0.8 с дольше"),

            // ---- the talent tree: branches and refusals -------------------------------
            (LocKey.BranchWarlord, "Полководец"),
            (LocKey.BranchWarden, "Защитник"),
            (LocKey.BranchZealot, "Фанатик"),
            (LocKey.BranchCrossroads, "Перепутье"),
            (LocKey.TalentUnknown, "Неизвестный талант"),
            (LocKey.TalentFullyRanked, "Полностью изучен"),
            (LocKey.TalentNoPoints, "Нет очков"),
            (LocKey.TalentRuledOut, "{0} исключает его"),
            (LocKey.TalentNeedsBoth, "Нужно {0} очков в ветвях {1} и {2}"),
            (LocKey.TalentNeedsBranch, "Нужно {0} очков в ветви {1}"),
            (LocKey.TalentNotLearned, "Не изучен"),
            (LocKey.TalentUnlearnFirst, "Сначала забудь {0}"),

            // ---- stat names, and the two shapes a stat value is written in ------------
            (LocKey.StatDamage, "Мощь"),
            (LocKey.StatHealth, "Живучесть"),
            (LocKey.StatCooldown, "Сосредоточение"),
            (LocKey.StatSpellPower, "Заклинание"),
            (LocKey.StatGateYield, "Ворота"),
            (LocKey.StatRunSpeed, "Скорость"),
            (LocKey.StatEnemyResist, "Стойкость"),
            (LocKey.StatShieldDuration, "Щит"),
            (LocKey.StatSpellCharges, "Заряды заклинаний"),
            (LocKey.StatShieldCharges, "Заряды щита"),
            (LocKey.StatFortune, "Удача"),
            (LocKey.StatGateCrit, "Крит ворот"),
            (LocKey.StatOverflowBank, "Излишек"),
            (LocKey.StatChainMultiply, "Цепь"),
            (LocKey.StatMagnetism, "Притяжение"),
            (LocKey.StatPackShatter, "Раскол"),
            (LocKey.StatSecondWind, "Второе дыхание"),
            (LocKey.StatExecute, "Добивание"),
            (LocKey.StatSpellEcho, "Эхо"),
            (LocKey.StatShieldReflect, "Отражение"),
            (LocKey.StatAffixPercent, "{0}{1}% {2}"),
            (LocKey.StatAffixFlat, "{0}{1} {2}"),
            (LocKey.StatTotalPercent, "{0} {1}%"),
            (LocKey.StatTotalFlat, "{0} {1}"),
            (LocKey.StatNone, "Нет бонусов"),

            // ---- the screens, the loot, and the authored content ----------------------
            (LocKey.GameTitle, "BATTLE RUNNER"),
            (LocKey.MenuTagline, "марш. умножай. убивай."),
            (LocKey.MenuSetForth, "В ПОХОД"),
            (LocKey.MenuChangeSlot, "СМЕНИТЬ ЯЧЕЙКУ"),
            (LocKey.MenuSoundOn, "ЗВУК ВКЛ"),
            (LocKey.MenuSoundOff, "ЗВУК ВЫКЛ"),
            (LocKey.MenuLanguage, "ЯЗЫК"),
            (LocKey.MenuLevelLine, "Уровень {0} — {1}"),
            (LocKey.SlotChooseWar, "выбери свою войну"),
            (LocKey.SlotErase, "СТЕРЕТЬ"),
            (LocKey.ConfirmSure, "ТОЧНО?"),
            (LocKey.HeroChooseTitle, "ВЫБЕРИ ЗАЩИТНИКА"),
            (LocKey.HeroChooseNote, "этот выбор — на всю эту игру"),
            (LocKey.HeroShowMe, "ПОКАЖИ"),
            (LocKey.HeroBegin, "НАЧАТЬ"),
            (LocKey.HudSpellReady, "ЗАКЛ ^ {0}"),
            (LocKey.HudSpellRefill, "ЗАКЛ {0} {1}"),
            (LocKey.HudShielded, "ПОД ЩИТОМ {0}"),
            (LocKey.HudShieldReady, "ЩИТ v {0}"),
            (LocKey.HudShieldRefill, "ЩИТ {0} {1}"),
            (LocKey.HudRound, "{0}-{1}   {2}"),
            (LocKey.HudBossAwaits, "{0} ЖДЁТ"),
            (LocKey.HudBossUnknown, "НЕЧТО"),
            (LocKey.LootBossYields, "БОСС ОТДАЁТ..."),
            (LocKey.LootBossYieldsTwice, "БОСС ОТДАЁТ... ДВАЖДЫ!"),
            (LocKey.LootSpoils, "ДОБЫЧА С ДОРОГИ"),
            (LocKey.LootDoubleAd, "ДВОЙНАЯ ДОБЫЧА  (РЕКЛАМА)"),
            (LocKey.LootAutoEquip, "НАДЕТЬ И ПРОДОЛЖИТЬ"),
            (LocKey.LootItemLine, "{0}\n<size=30>{1} {2}</size>"),
            (LocKey.LootPowerEquipped, "Сила предмета {0}  — надето!"),
            (LocKey.LootPowerKept, "Сила предмета {0}  — в сумке"),
            (LocKey.RarityCommon, "Обычное"),
            (LocKey.RarityRare, "Редкое"),
            (LocKey.RarityEpic, "Эпическое"),
            (LocKey.RarityLegendary, "Легендарное"),
            (LocKey.GearSlotWeapon, "Оружие"),
            (LocKey.GearSlotArmor, "Броня"),
            (LocKey.GearSlotRelic, "Реликвия"),
            (LocKey.GearNone, "снаряжения пока нет"),
            (LocKey.Dash, "—"),
            (LocKey.ResurrectFallen, "ТВОЁ ВОЙСКО ПАЛО"),
            (LocKey.ResurrectAd, "ВОСКРЕСИТЬ  (РЕКЛАМА)"),
            (LocKey.ResurrectGiveUp, "ПРИНЯТЬ ПОРАЖЕНИЕ"),
            (LocKey.TreeTitle, "СТАНЬ СИЛЬНЕЕ"),
            (LocKey.TreeContinue, "ПРОДОЛЖИТЬ"),
            (LocKey.TreeForgetAll, "ЗАБЫТЬ ВСЁ"),
            (LocKey.TreeEndless, "БЕЗ КОНЦА — каждое очко на счету"),
            (LocKey.TabWarlord, "ПОЛКОВОДЕЦ"),
            (LocKey.TabWarden, "ЗАЩИТНИК"),
            (LocKey.TabZealot, "ФАНАТИК"),
            (LocKey.TabHybrid, "ГИБРИД"),
            (LocKey.TabParagon, "ПАРАГОН"),
            (LocKey.TreeNeedsBothTier, "НУЖНО {0} В ОБЕИХ ВЕТВЯХ"),
            (LocKey.TreeTierLine, "УРОВЕНЬ {0} · {1} ОЧКОВ В ВЕТВИ"),
            (LocKey.TreeKeystoneChoose, "КРАЕУГОЛЬНЫЙ — ВЫБЕРИ ОДИН"),
            (LocKey.TreeReady, "ГОТОВО"),
            (LocKey.TreeTapAgain, "НАЖМИ - ЕЩЁ РАЗ"),
            (LocKey.TreePointsToSpend, "{0} очко на трату|{0} очка на трату|{0} очков на трату"),
            (LocKey.TreePointsSpent, "Потрачено {0} очко · нажми - на таланте, чтобы вернуть|Потрачено {0} очка · нажми - на таланте, чтобы вернуть|Потрачено {0} очков · нажми - на таланте, чтобы вернуть"),
            (LocKey.TreeParagonRanks, "{0} ранг парагона · каждый ранг дороже и даёт чуть меньше|{0} ранга парагона · каждый ранг дороже и даёт чуть меньше|{0} рангов парагона · каждый ранг дороже и даёт чуть меньше"),
            (LocKey.TreeParagonLocked, "Закрыто, пока не возьмёшь краеугольный талант"),
            (LocKey.TreeParagonOpens, "Парагон открывается, как только возьмёшь краеугольный талант."),
            (LocKey.TreeSpendFour, "Вложи четыре очка в ветвь, чтобы открыть её следующий уровень."),
            (LocKey.TreeRankLine, "Ранг {0} · {1} · следующий стоит {2}"),
            (LocKey.TreeGiveBack, "Нажми - ещё раз, чтобы вернуть ранг: {0}."),
            (LocKey.TreeRefunded, "{0} — возвращено."),
            (LocKey.TreeDeepened, "{0} — углублено."),
            (LocKey.TreeForgotten, "Всё забыто. Трать очки заново."),
            (LocKey.TreeForgetConfirm, "Забыть все таланты и ранги парагона и вернуть все очки?"),
            (LocKey.StatMightDesc, "Чистый урон твоего героя и орды."),
            (LocKey.StatVigorDesc, "Смягчает удары босса по войску."),
            (LocKey.StatFocusDesc, "Сокращает откат заклинаний и щита."),
            (LocKey.BossBoneColossus, "Костяной Колосс"),
            (LocKey.BossEmberLich, "Тлеющий Лич"),
            (LocKey.BossGraveWarden, "Могильный Страж"),
            (LocKey.BossHollowLeech, "Полый Кровосос"),
            (LocKey.BossPaleShepherd, "Бледный Пастырь"),
            (LocKey.BossGoreHound, "Кровавый Пёс"),
            (LocKey.LevelAshenRoad, "Пепельный тракт"),
            (LocKey.LevelGallowsMire, "Висельная топь"),
            (LocKey.LevelSunkenCrypt, "Затонувший склеп"),
            (LocKey.LevelEmberFields, "Тлеющие поля"),
            (LocKey.LevelThroneOfDust, "Престол праха"),
            (LocKey.LevelWeepingGate, "Плачущие врата"),
            (LocKey.GearWpnRustedCleaverName, "Ржавый тесак"),
            (LocKey.GearWpnRustedCleaverFlavor, "Всё ещё помнит проигранную войну."),
            (LocKey.GearWpnGravediggerAxeName, "Топор могильщика"),
            (LocKey.GearWpnGravediggerAxeFlavor, "Затупился от честной мрачной работы."),
            (LocKey.GearWpnCinderBladeName, "Пепельный клинок"),
            (LocKey.GearWpnCinderBladeFlavor, "Тёплый на ощупь. Всегда."),
            (LocKey.GearWpnSoulreaverName, "Душегуб"),
            (LocKey.GearWpnSoulreaverFlavor, "Он пьёт. Ты держишь."),
            (LocKey.GearWpnDoombringerName, "Вестник гибели"),
            (LocKey.GearWpnDoombringerFlavor, "Последний клинок своего кузнеца."),
            (LocKey.GearArmTatteredHauberkName, "Драная кольчуга"),
            (LocKey.GearArmTatteredHauberkFlavor, "Дыр больше, чем колец."),
            (LocKey.GearArmBoneVestName, "Костяной жилет"),
            (LocKey.GearArmBoneVestFlavor, "Кости тут не для красоты."),
            (LocKey.GearArmIronbarkPlateName, "Железнокорые латы"),
            (LocKey.GearArmIronbarkPlateFlavor, "Выращены, а не выкованы."),
            (LocKey.GearArmWraithmailName, "Призрачная кольчуга"),
            (LocKey.GearArmWraithmailFlavor, "Невесомая. Шепчущая."),
            (LocKey.GearArmAegisFallenKingName, "Эгида павшего короля"),
            (LocKey.GearArmAegisFallenKingFlavor, "Он пал. Она — нет."),
            (LocKey.GearRelCrackedSkullName, "Оберег из треснувшего черепа"),
            (LocKey.GearRelCrackedSkullFlavor, "Прежнему владельцу повезло меньше."),
            (LocKey.GearRelEmberTalismanName, "Тлеющий талисман"),
            (LocKey.GearRelEmberTalismanFlavor, "Карман угасающего огня."),
            (LocKey.GearRelHollowIdolName, "Полый идол"),
            (LocKey.GearRelHollowIdolFlavor, "Внутри когда-то кто-то жил."),
            (LocKey.GearRelEyeOfAbyssName, "Око бездны"),
            (LocKey.GearRelEyeOfAbyssFlavor, "Моргает, когда ты колдуешь."),
            (LocKey.GearRelCrownOfEmbersName, "Корона из углей"),
            (LocKey.GearRelCrownOfEmbersFlavor, "Не правь ничем. Сожги всё."),

            // ---- save slots -----------------------------------------------------------
            (LocKey.SlotNumber, "ЯЧЕЙКА {0}"),
            (LocKey.SlotNewGame, "Новая игра"),
            (LocKey.SlotLevel, "Уровень {0}"),
            (LocKey.SlotTalents, "{0} талант|{0} таланта|{0} талантов"),
            (LocKey.SlotUnspent, "{0} не вложено")
        };

        public static readonly (LocKey Key, string Text)[] Hebrew =
        {
            // ---- the tutorial ---------------------------------------------------------
            // Infinitives, not imperatives. Hebrew imperatives carry gender — החלק to a man,
            // החליקי to a woman — and the game does not know which it is talking to.
            (LocKey.TutorialSteerTitle, "להחליק כדי לנווט"),
            (LocKey.TutorialSteerDetail, "להחליק את האגודל שמאלה או ימינה"),
            (LocKey.TutorialGateTitle, "לבחור בשער הגדול"),
            (LocKey.TutorialGateDetail, "כחול מוסיף, זהב מכפיל, אדום לוקח"),
            (LocKey.TutorialCastTitle, "תנועה מהירה למעלה - לחש"),
            (LocKey.TutorialCastDetail, "להרים את האגודל ואז להחליק מהר למעלה"),
            (LocKey.TutorialBlockTitle, "תנועה מהירה למטה - מגן"),
            (LocKey.TutorialBlockDetail, "להרים את האגודל ואז להחליק מהר למטה"),

            // ---- the four heroes ------------------------------------------------------
            (LocKey.HeroWardenName, "השומר"),
            (LocKey.HeroWardenTagline, "מחזיק את הקו. שני מגנים, ומארב שנחסם מצטרף אליך."),
            (LocKey.HeroAshcallerName, "קורא האפר"),
            (LocKey.HeroAshcallerTagline, "שורף את הדרך שלפניו. שני לחשים, והם מגיעים רחוק יותר."),
            (LocKey.HeroHoundmasterName, "אדון הכלבים"),
            (LocKey.HeroHoundmasterTagline, "שני כלבים באגף. כל שער גיוס משלם יותר."),
            (LocKey.HeroRevenantName, "השב"),
            (LocKey.HeroRevenantTagline, "הנופלים חוזרים. את מה שאיבדת תקבל ברובו בחזרה."),

            // ---- the eight worlds -----------------------------------------------------
            (LocKey.WorldAshenRoad, "דרך האפר"),
            (LocKey.WorldThistlewood, "יער הדרדר"),
            (LocKey.WorldSunkenCrypt, "הכוך הטבוע"),
            (LocKey.WorldEmberFields, "שדות הגחלים"),
            (LocKey.WorldBoneWastes, "שממות העצם"),
            (LocKey.WorldFrozenReach, "המרחב הקפוא"),
            (LocKey.WorldBloodMarsh, "ביצת הדם"),
            (LocKey.WorldThroneOfDust, "כס האבק"),

            // ---- boss affixes ---------------------------------------------------------
            (LocKey.AffixFrenzied, "המשתולל"),
            (LocKey.AffixArmoured, "המשוריין"),
            (LocKey.AffixVampiric, "מוצץ הדם"),
            (LocKey.AffixHaunted, "הרדוף"),
            (LocKey.AffixColossal, "הענק"),
            // REVERSED, and this is the reason the pairing is a template at all: a Hebrew
            // adjective follows the noun it describes, so the boss's name comes first.
            (LocKey.AffixDecorate, "{1} {0}"),

            // ---- paragon --------------------------------------------------------------
            (LocKey.ParagonMight, "עוצמה"),
            (LocKey.ParagonVigor, "חוסן"),
            (LocKey.ParagonGates, "שערים"),
            (LocKey.ParagonFortune, "מזל"),
            (LocKey.ParagonFocus, "ריכוז"),
            (LocKey.ParagonSpeed, "מהירות"),
            (LocKey.ParagonUnknownPath, "נתיב לא מוכר"),
            (LocKey.ParagonNeedKeystone, "קודם צריך להגיע לאבן פינה"),
            (LocKey.ParagonCostsPoints, "עולה נקודה אחת|עולה {0} נקודות"),

            // ---- the talent tree ------------------------------------------------------
            (LocKey.TalentWlEdgeName, "להב חד"),
            (LocKey.TalentWlEdgeDesc, "+3 עוצמה"),
            (LocKey.TalentWlFocusName, "ריכוז קר"),
            (LocKey.TalentWlFocusDesc, "+3% ריכוז"),
            (LocKey.TalentWlSpiteName, "זדון"),
            (LocKey.TalentWlSpiteDesc, "+6% נזק לחשים"),
            (LocKey.TalentWlCleaveName, "בקיעה"),
            (LocKey.TalentWlCleaveDesc, "+4% עוצמה"),
            (LocKey.TalentWlTemperName, "חישול"),
            (LocKey.TalentWlTemperDesc, "+8% נזק לחשים"),
            (LocKey.TalentWlGrindName, "אבן משחזת"),
            (LocKey.TalentWlGrindDesc, "+5 עוצמה"),
            (LocKey.TalentWlHasteName, "זירוז"),
            (LocKey.TalentWlHasteDesc, "+4% ריכוז"),
            (LocKey.TalentWlWrathName, "זעם"),
            (LocKey.TalentWlWrathDesc, "+5% עוצמה"),
            (LocKey.TalentWlRuinName, "חורבן"),
            (LocKey.TalentWlRuinDesc, "+7 עוצמה"),
            (LocKey.TalentWlSurgeName, "נחשול"),
            (LocKey.TalentWlSurgeDesc, "+10% נזק לחשים"),
            (LocKey.TalentWlMaliceName, "מזימה"),
            (LocKey.TalentWlMaliceDesc, "+6% עוצמה"),
            (LocKey.TalentWlVenomName, "ארס"),
            (LocKey.TalentWlVenomDesc, "+12% נזק לחשים"),
            (LocKey.TalentWlUrgencyName, "דחיפות"),
            (LocKey.TalentWlUrgencyDesc, "+5% ריכוז"),
            (LocKey.TalentWdHideName, "עור עבה"),
            (LocKey.TalentWdHideDesc, "+18 חוסן"),
            (LocKey.TalentWdGuardName, "שמירה"),
            (LocKey.TalentWdGuardDesc, "חוליות עולות 4% פחות"),
            (LocKey.TalentWdBraceName, "התכוננות"),
            (LocKey.TalentWdBraceDesc, "המגן מחזיק 0.2 שניות יותר"),
            (LocKey.TalentWdPlateName, "שריון לוחות"),
            (LocKey.TalentWdPlateDesc, "+4% חוסן"),
            (LocKey.TalentWdBrambleName, "סבך קוצים"),
            (LocKey.TalentWdBrambleDesc, "חוליות עולות 5% פחות"),
            (LocKey.TalentWdStoneName, "דם אבן"),
            (LocKey.TalentWdStoneDesc, "+24 חוסן"),
            (LocKey.TalentWdWardName, "הגנה"),
            (LocKey.TalentWdWardDesc, "המגן מחזיק 0.25 שניות יותר"),
            (LocKey.TalentWdScarName, "צלקות"),
            (LocKey.TalentWdScarDesc, "חוליות עולות 5% פחות"),
            (LocKey.TalentWdReadyName, "בכוננות"),
            (LocKey.TalentWdReadyDesc, "המגן חוזר 4% מהר יותר"),
            (LocKey.TalentWdBastionName, "מצודה"),
            (LocKey.TalentWdBastionDesc, "+6% חוסן"),
            (LocKey.TalentWdThornsName, "קוצים"),
            (LocKey.TalentWdThornsDesc, "12% החזרה"),
            (LocKey.TalentWdIronName, "כבול בברזל"),
            (LocKey.TalentWdIronDesc, "+34 חוסן"),
            (LocKey.TalentWdDenyName, "סירוב"),
            (LocKey.TalentWdDenyDesc, "חוליות עולות 6% פחות"),
            (LocKey.TalentWdShellName, "שריון"),
            (LocKey.TalentWdShellDesc, "10% ניפוץ"),
            (LocKey.TalentZlAvariceName, "חמדנות"),
            (LocKey.TalentZlAvariceDesc, "+3% מכל שער"),
            (LocKey.TalentZlStrideName, "צעד"),
            (LocKey.TalentZlStrideDesc, "+2% מהירות"),
            (LocKey.TalentZlLuckName, "מזל"),
            (LocKey.TalentZlLuckDesc, "+6% שלל נדיר"),
            (LocKey.TalentZlGreedName, "תאוות בצע"),
            (LocKey.TalentZlGreedDesc, "+4% מכל שער"),
            (LocKey.TalentZlLodestoneName, "אבן שואבת"),
            (LocKey.TalentZlLodestoneDesc, "שערים מגיעים 0.12 מטר רחוק יותר"),
            (LocKey.TalentZlTitheName, "מעשר"),
            (LocKey.TalentZlTitheDesc, "+5% מכל שער"),
            (LocKey.TalentZlOmenName, "אות מבשר"),
            (LocKey.TalentZlOmenDesc, "+8% שלל נדיר"),
            (LocKey.TalentZlFervourName, "להט"),
            (LocKey.TalentZlFervourDesc, "4% קריטי בשער"),
            (LocKey.TalentZlHungerName, "רעב"),
            (LocKey.TalentZlHungerDesc, "+6% מכל שער"),
            (LocKey.TalentZlPullName, "משיכה"),
            (LocKey.TalentZlPullDesc, "שערים מגיעים 0.15 מטר רחוק יותר"),
            (LocKey.TalentZlRaptureName, "התעלות"),
            (LocKey.TalentZlRaptureDesc, "+7% מכל שער"),
            (LocKey.TalentZlFrenzyName, "טירוף"),
            (LocKey.TalentZlFrenzyDesc, "+3% מהירות"),
            (LocKey.TalentZlCascadeName, "ספירלה"),
            (LocKey.TalentZlCascadeDesc, "+8% שרשרת"),
            (LocKey.TalentWlEchoName, "מילה מהדהדת"),
            (LocKey.TalentWlEchoDesc, "12% סיכוי שהלחש יוטל פעמיים"),
            (LocKey.TalentWlLanceName, "שבירה"),
            (LocKey.TalentWlLanceDesc, "+22% נזק לחשים, +6 עוצמה"),
            (LocKey.TalentWlQuiverName, "אשפה מלאה"),
            (LocKey.TalentWlQuiverDesc, "אפשר להחזיק לחש שני"),
            (LocKey.TalentWlExecuteName, "תליין"),
            (LocKey.TalentWlExecuteDesc, "בוס מתחת ל-8% חיים מת מיד"),
            (LocKey.TalentWlReapName, "חוב הקוצר"),
            (LocKey.TalentWlReapDesc, "סף ההוצאה להורג +7%"),
            (LocKey.TalentWlSwiftName, "זריזות"),
            (LocKey.TalentWlSwiftDesc, "+9% ריכוז, 10% הד לחשים"),
            (LocKey.TalentWlArsenalName, "מחסן נשק"),
            (LocKey.TalentWlArsenalDesc, "אפשר להחזיק לחש שלישי"),
            (LocKey.TalentWlCarnageName, "טבח"),
            (LocKey.TalentWlCarnageDesc, "+14 עוצמה ו-+20% נזק לחשים"),
            (LocKey.TalentWdShatterName, "מגן מנפץ"),
            (LocKey.TalentWdShatterDesc, "14% סיכוי שחוליה מתנפצת ולא עולה דבר"),
            (LocKey.TalentWdDoubleguardName, "הגנה כפולה"),
            (LocKey.TalentWdDoubleguardDesc, "אפשר להרים מגן פעם שנייה"),
            (LocKey.TalentWdBulwarkName, "חומה"),
            (LocKey.TalentWdBulwarkDesc, "המגן מחזיק שנייה 1 יותר, +30 חוסן"),
            (LocKey.TalentWdReflectName, "תגובת נגד"),
            (LocKey.TalentWdReflectDesc, "מכה שנחסמה מחזירה לבוס 25% ממנה"),
            (LocKey.TalentWdWindName, "נשימה שנייה"),
            (LocKey.TalentWdWindDesc, "פעם אחת בריצה, מוות מחזיר 30% מהצבא"),
            (LocKey.TalentWdAegisName, "מגן האלים"),
            (LocKey.TalentWdAegisDesc, "המגן מחזיק 1.4 שניות יותר, 18% ניפוץ"),
            (LocKey.TalentWdTriguardName, "הגנה משולשת"),
            (LocKey.TalentWdTriguardDesc, "אפשר להרים מגן פעם שלישית"),
            (LocKey.TalentWdUnbrokenName, "בלתי שבור"),
            (LocKey.TalentWdUnbrokenDesc, "+70 חוסן, חוליות עולות 12% פחות"),
            (LocKey.TalentZlCritName, "קנאות"),
            (LocKey.TalentZlCritDesc, "10% סיכוי ששער נספר פעמיים"),
            (LocKey.TalentZlZealName, "התלהבות"),
            (LocKey.TalentZlZealDesc, "+12% מהירות, +8% מהשערים"),
            (LocKey.TalentZlChainName, "מפל"),
            (LocKey.TalentZlChainDesc, "כל שער x רצוף מוסיף 15% יותר"),
            (LocKey.TalentZlHoardName, "אוצר"),
            (LocKey.TalentZlHoardDesc, "עודף מעבר לתקרה חוזר כ-25% נזק לבוס"),
            (LocKey.TalentZlSwarmName, "נחיל"),
            (LocKey.TalentZlSwarmDesc, "+18% מהשערים, 12% קריטי בשער"),
            (LocKey.TalentZlLegionName, "לגיון"),
            (LocKey.TalentZlLegionDesc, "+25% מהשערים, +20% שלל נדיר"),
            (LocKey.TalentWlAnnihilationName, "השמדה"),
            (LocKey.TalentWlAnnihilationDesc, "+40% עוצמה, +60% נזק לחשים"),
            (LocKey.TalentWlHeadsmanName, "הכורת"),
            (LocKey.TalentWlHeadsmanDesc, "סף ההוצאה להורג +20%"),
            (LocKey.TalentWlTempestName, "סערה"),
            (LocKey.TalentWlTempestDesc, "עוד שני לחשים, 45% הד, +25% ריכוז"),
            (LocKey.TalentWdUndyingName, "בן אלמוות"),
            (LocKey.TalentWdUndyingDesc, "+120 חוסן, נשימה שנייה מחזירה 55%"),
            (LocKey.TalentWdImmovableName, "בלתי נזיז"),
            (LocKey.TalentWdImmovableDesc, "חוליות עולות 40% פחות, 30% ניפוץ"),
            (LocKey.TalentWdMirrorName, "מראת הקוצים"),
            (LocKey.TalentWdMirrorDesc, "עוד שתי הרמות מגן, מכות חסומות מחזירות 90%"),
            (LocKey.TalentZlMultiplicationName, "הכפלה"),
            (LocKey.TalentZlMultiplicationDesc, "+55% מהשערים, 25% קריטי בשער"),
            (LocKey.TalentZlAvalancheName, "מפולת"),
            (LocKey.TalentZlAvalancheDesc, "שרשרת +60%, שערים מגיעים 0.5 מטר רחוק יותר"),
            (LocKey.TalentZlCovetousName, "חומד"),
            (LocKey.TalentZlCovetousDesc, "עודף מחזיר 90%, +60% שלל נדיר"),
            (LocKey.TalentCrWarpriestName, "כוהן מלחמה"),
            (LocKey.TalentCrWarpriestDesc, "+10 עוצמה, +8% מהשערים"),
            (LocKey.TalentCrCrusaderName, "צלבן"),
            (LocKey.TalentCrCrusaderDesc, "+40 חוסן, +12% נזק לחשים"),
            (LocKey.TalentCrPilgrimName, "עולה רגל"),
            (LocKey.TalentCrPilgrimDesc, "חוליות עולות 10% פחות, +6% מהירות"),
            (LocKey.TalentCrMartyrName, "קדוש מעונה"),
            (LocKey.TalentCrMartyrDesc, "מכות חסומות מחזירות 30%, +12 עוצמה"),
            (LocKey.TalentCrProphetName, "נביא"),
            (LocKey.TalentCrProphetDesc, "עודף מחזיר 30%, +18% נזק לחשים"),
            (LocKey.TalentCrShepherdName, "רועה"),
            (LocKey.TalentCrShepherdDesc, "18% ניפוץ, +14% מהשערים"),
            (LocKey.TalentCrApostleName, "שליח"),
            (LocKey.TalentCrApostleDesc, "הוצאה להורג +6%, שרשרת +20%"),
            (LocKey.TalentCrPaladinName, "פלאדין"),
            (LocKey.TalentCrPaladinDesc, "+80 חוסן, +18 עוצמה, המגן מחזיק 0.8 שניות יותר"),

            // ---- the talent tree: branches and refusals -------------------------------
            (LocKey.BranchWarlord, "מצביא"),
            (LocKey.BranchWarden, "מגן"),
            (LocKey.BranchZealot, "קנאי"),
            (LocKey.BranchCrossroads, "פרשת דרכים"),
            (LocKey.TalentUnknown, "כישרון לא מוכר"),
            (LocKey.TalentFullyRanked, "מפותח במלואו"),
            (LocKey.TalentNoPoints, "אין נקודות לבזבז"),
            (LocKey.TalentRuledOut, "{0} פוסל אותו"),
            (LocKey.TalentNeedsBoth, "דרושות {0} נקודות ב{1} וב{2}"),
            (LocKey.TalentNeedsBranch, "דרושות {0} נקודות ב{1}"),
            (LocKey.TalentNotLearned, "לא נלמד"),
            (LocKey.TalentUnlearnFirst, "קודם לשכוח את {0}"),

            // ---- stat names, and the two shapes a stat value is written in ------------
            (LocKey.StatDamage, "עוצמה"),
            (LocKey.StatHealth, "חוסן"),
            (LocKey.StatCooldown, "ריכוז"),
            (LocKey.StatSpellPower, "לחש"),
            (LocKey.StatGateYield, "שערים"),
            (LocKey.StatRunSpeed, "מהירות"),
            (LocKey.StatEnemyResist, "עמידות"),
            (LocKey.StatShieldDuration, "מגן"),
            (LocKey.StatSpellCharges, "מטעני לחש"),
            (LocKey.StatShieldCharges, "מטעני מגן"),
            (LocKey.StatFortune, "מזל"),
            (LocKey.StatGateCrit, "קריטי בשער"),
            (LocKey.StatOverflowBank, "עודף"),
            (LocKey.StatChainMultiply, "שרשרת"),
            (LocKey.StatMagnetism, "משיכה"),
            (LocKey.StatPackShatter, "ניפוץ"),
            (LocKey.StatSecondWind, "נשימה שנייה"),
            (LocKey.StatExecute, "הוצאה להורג"),
            (LocKey.StatSpellEcho, "הד"),
            (LocKey.StatShieldReflect, "החזרה"),
            (LocKey.StatAffixPercent, "{0}{1}% {2}"),
            (LocKey.StatAffixFlat, "{0}{1} {2}"),
            (LocKey.StatTotalPercent, "{0} {1}%"),
            (LocKey.StatTotalFlat, "{0} {1}"),
            (LocKey.StatNone, "אין בונוסים"),

            // ---- the screens, the loot, and the authored content ----------------------
            (LocKey.GameTitle, "BATTLE RUNNER"),
            (LocKey.MenuTagline, "לצעוד. להכפיל. להרוג."),
            (LocKey.MenuSetForth, "לצאת לדרך"),
            (LocKey.MenuChangeSlot, "להחליף משבצת"),
            (LocKey.MenuSoundOn, "צליל דלוק"),
            (LocKey.MenuSoundOff, "צליל כבוי"),
            (LocKey.MenuLanguage, "שפה"),
            (LocKey.MenuLevelLine, "שלב {0} — {1}"),
            (LocKey.SlotChooseWar, "לבחור את המלחמה שלך"),
            (LocKey.SlotErase, "למחוק"),
            (LocKey.ConfirmSure, "בטוח?"),
            (LocKey.HeroChooseTitle, "לבחור את הגיבור"),
            (LocKey.HeroChooseNote, "הבחירה הזו היא לכל חיי השמירה הזו"),
            (LocKey.HeroShowMe, "להראות"),
            (LocKey.HeroBegin, "להתחיל"),
            (LocKey.HudSpellReady, "לחש ^ {0}"),
            (LocKey.HudSpellRefill, "לחש {0} {1}"),
            (LocKey.HudShielded, "מוגן {0}"),
            (LocKey.HudShieldReady, "מגן v {0}"),
            (LocKey.HudShieldRefill, "מגן {0} {1}"),
            (LocKey.HudRound, "{0}-{1}   {2}"),
            (LocKey.HudBossAwaits, "{0} ממתין"),
            (LocKey.HudBossUnknown, "משהו"),
            (LocKey.LootBossYields, "הבוס מוותר..."),
            (LocKey.LootBossYieldsTwice, "הבוס מוותר... פעמיים!"),
            (LocKey.LootSpoils, "שלל הדרך"),
            (LocKey.LootDoubleAd, "שלל כפול  (פרסומת)"),
            (LocKey.LootAutoEquip, "לצייד ולהמשיך"),
            (LocKey.LootItemLine, "{0}\n<size=30>{1} {2}</size>"),
            (LocKey.LootPowerEquipped, "עוצמת פריט {0}  — צויד!"),
            (LocKey.LootPowerKept, "עוצמת פריט {0}  — נשמר בתיק"),
            (LocKey.RarityCommon, "רגיל"),
            (LocKey.RarityRare, "נדיר"),
            (LocKey.RarityEpic, "אפי"),
            (LocKey.RarityLegendary, "אגדי"),
            (LocKey.GearSlotWeapon, "נשק"),
            (LocKey.GearSlotArmor, "שריון"),
            (LocKey.GearSlotRelic, "קמע"),
            (LocKey.GearNone, "אין ציוד עדיין"),
            (LocKey.Dash, "—"),
            (LocKey.ResurrectFallen, "הצבא שלך נפל"),
            (LocKey.ResurrectAd, "להחיות  (פרסומת)"),
            (LocKey.ResurrectGiveUp, "לקבל את התבוסה"),
            (LocKey.TreeTitle, "להתחזק"),
            (LocKey.TreeContinue, "להמשיך"),
            (LocKey.TreeForgetAll, "לשכוח הכל"),
            (LocKey.TreeEndless, "אינסופי — כל נקודה עדיין נחשבת"),
            (LocKey.TabWarlord, "מצביא"),
            (LocKey.TabWarden, "מגן"),
            (LocKey.TabZealot, "קנאי"),
            (LocKey.TabHybrid, "משולב"),
            (LocKey.TabParagon, "פראגון"),
            (LocKey.TreeNeedsBothTier, "דרושות {0} בשני הענפים"),
            (LocKey.TreeTierLine, "דרג {0} · {1} נקודות בענף"),
            (LocKey.TreeKeystoneChoose, "אבן פינה — לבחור אחת"),
            (LocKey.TreeReady, "מוכן"),
            (LocKey.TreeTapAgain, "ללחוץ - שוב"),
            (LocKey.TreePointsToSpend, "נקודה אחת לבזבז|{0} נקודות לבזבז"),
            (LocKey.TreePointsSpent, "הושקעה נקודה אחת · ללחוץ - על כישרון כדי להחזיר|הושקעו {0} נקודות · ללחוץ - על כישרון כדי להחזיר"),
            (LocKey.TreeParagonRanks, "דרגת פראגון אחת · כל דרגה עולה יותר ונותנת קצת פחות|{0} דרגות פראגון · כל דרגה עולה יותר ונותנת קצת פחות"),
            (LocKey.TreeParagonLocked, "נעול עד שלוקחים אבן פינה"),
            (LocKey.TreeParagonOpens, "הפראגון נפתח ברגע שלוקחים אבן פינה."),
            (LocKey.TreeSpendFour, "להשקיע ארבע נקודות בענף כדי לפתוח את הדרג הבא שלו."),
            (LocKey.TreeRankLine, "דרגה {0} · {1} · הבאה עולה {2}"),
            (LocKey.TreeGiveBack, "ללחוץ - שוב כדי להחזיר דרגה של {0}."),
            (LocKey.TreeRefunded, "{0} הוחזר."),
            (LocKey.TreeDeepened, "{0} הועמק."),
            (LocKey.TreeForgotten, "הכל נשכח. להשקיע את הנקודות מחדש."),
            (LocKey.TreeForgetConfirm, "לשכוח כל כישרון וכל דרגת פראגון ולקבל את כל הנקודות בחזרה?"),
            (LocKey.StatMightDesc, "נזק גולמי של הגיבור והמון שלך."),
            (LocKey.StatVigorDesc, "מרכך את מכות הבוס על הצבא."),
            (LocKey.StatFocusDesc, "מקצר את זמני ההמתנה של לחש ומגן."),
            (LocKey.BossBoneColossus, "קולוסוס העצם"),
            (LocKey.BossEmberLich, "ליץ' הגחלים"),
            (LocKey.BossGraveWarden, "שומר הקברים"),
            (LocKey.BossHollowLeech, "מוצץ הדם החלול"),
            (LocKey.BossPaleShepherd, "הרועה החיוור"),
            (LocKey.BossGoreHound, "כלב הדמים"),
            (LocKey.LevelAshenRoad, "דרך האפר"),
            (LocKey.LevelGallowsMire, "ביצת הגרדום"),
            (LocKey.LevelSunkenCrypt, "הכוך הטבוע"),
            (LocKey.LevelEmberFields, "שדות הגחלים"),
            (LocKey.LevelThroneOfDust, "כס האבק"),
            (LocKey.LevelWeepingGate, "השער הבוכה"),
            (LocKey.GearWpnRustedCleaverName, "קופיץ חלוד"),
            (LocKey.GearWpnRustedCleaverFlavor, "עדיין זוכר את המלחמה שהפסיד."),
            (LocKey.GearWpnGravediggerAxeName, "גרזן קברן"),
            (LocKey.GearWpnGravediggerAxeFlavor, "קהה מעבודה כנה וקודרת."),
            (LocKey.GearWpnCinderBladeName, "להב גחלים"),
            (LocKey.GearWpnCinderBladeFlavor, "חמים למגע. תמיד."),
            (LocKey.GearWpnSoulreaverName, "קוטל הנשמות"),
            (LocKey.GearWpnSoulreaverFlavor, "הוא שותה. אתה אוחז."),
            (LocKey.GearWpnDoombringerName, "מבשר החורבן"),
            (LocKey.GearWpnDoombringerFlavor, "הלהב האחרון שנפחו יצר אי פעם."),
            (LocKey.GearArmTatteredHauberkName, "שריון קרוע"),
            (LocKey.GearArmTatteredHauberkFlavor, "יותר חורים מטבעות."),
            (LocKey.GearArmBoneVestName, "אפוד עצמות"),
            (LocKey.GearArmBoneVestFlavor, "העצמות אינן לקישוט."),
            (LocKey.GearArmIronbarkPlateName, "שריון קליפת ברזל"),
            (LocKey.GearArmIronbarkPlateFlavor, "גודל, לא נוצר בכור."),
            (LocKey.GearArmWraithmailName, "שריון הרפאים"),
            (LocKey.GearArmWraithmailFlavor, "חסר משקל. לוחש."),
            (LocKey.GearArmAegisFallenKingName, "מגן המלך הנופל"),
            (LocKey.GearArmAegisFallenKingFlavor, "הוא נפל. הוא לא."),
            (LocKey.GearRelCrackedSkullName, "קמע גולגולת סדוקה"),
            (LocKey.GearRelCrackedSkullFlavor, "לבעליו הקודם היה פחות מזל."),
            (LocKey.GearRelEmberTalismanName, "קמע גחלים"),
            (LocKey.GearRelEmberTalismanFlavor, "כיס מלא אש גוועת."),
            (LocKey.GearRelHollowIdolName, "אליל חלול"),
            (LocKey.GearRelHollowIdolFlavor, "פעם משהו חי בפנים."),
            (LocKey.GearRelEyeOfAbyssName, "עין התהום"),
            (LocKey.GearRelEyeOfAbyssFlavor, "היא ממצמצת כשמטילים לחש."),
            (LocKey.GearRelCrownOfEmbersName, "כתר הגחלים"),
            (LocKey.GearRelCrownOfEmbersFlavor, "לא למשול בדבר. לשרוף הכל."),

            // ---- save slots -----------------------------------------------------------
            (LocKey.SlotNumber, "משבצת {0}"),
            (LocKey.SlotNewGame, "משחק חדש"),
            (LocKey.SlotLevel, "שלב {0}"),
            (LocKey.SlotTalents, "כישרון אחד|{0} כישרונות"),
            (LocKey.SlotUnspent, "{0} לא הושקעו")
        };
    }
}
